'use client';

import { useState, useEffect } from 'react';
import { useRouter, useParams } from 'next/navigation';
import { Container, Card } from '@/components/ui';
import { OptimizationStorage, OptimizationState } from '@/lib/optimizationState';
import tokens from '@/design-system/tokens.json';

export default function FinishPage() {
  const router = useRouter();
  const params = useParams();
  const [showToast, setShowToast] = useState(false);
  const [optimizedContent, setOptimizedContent] = useState<any>(null);
  const [isLoading, setIsLoading] = useState(true);

  useEffect(() => {
    loadOptimization();
  }, [params.id]);

  const loadOptimization = () => {
    try {
      const state = OptimizationStorage.get(params.id as string);
      
      if (!state) {
        console.error('No optimization found');
        router.push('/upload');
        return;
      }

      // Build final content from user's selections
      const finalTitle = state.title.selected === 'suggested' 
        ? state.title.suggested 
        : state.title.current;
      
      const finalDescription = state.description.selected === 'suggested'
        ? state.description.suggested
        : state.description.current;

      setOptimizedContent({
        photo: state.photo.selected === 'improved' ? state.photo.improved : state.photo.original,
        title: finalTitle,
        tags: state.keywords.selected,
        description: finalDescription,
        score: state.score.potential,
        maxScore: 285
      });
    } catch (error) {
      console.error('Load error:', error);
    } finally {
      setIsLoading(false);
    }
  };

  const handleDownloadText = () => {
    if (!optimizedContent) return;

    const textContent = `OPTIMIZED ETSY LISTING

TITLE:
${optimizedContent.title}

TAGS:
${optimizedContent.tags.join(', ')}

DESCRIPTION:
${optimizedContent.description}

Generated by Elite Listing AI
Date: ${new Date().toLocaleString()}
`;

    const blob = new Blob([textContent], { type: 'text/plain' });
    const url = window.URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `etsy-listing-${Date.now()}.txt`;
    a.click();
    window.URL.revokeObjectURL(url);

    setShowToast(true);
    setTimeout(() => setShowToast(false), 2000);
  };

  const handleSaveToAccount = async () => {
    if (!optimizedContent) return;

    try {
      // Save to database via API
      const response = await fetch('/api/optimizations', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          type: 'full',
          status: 'completed',
          result: {
            photo: optimizedContent.photo,
            title: optimizedContent.title,
            tags: optimizedContent.tags,
            description: optimizedContent.description,
            score: optimizedContent.score
          }
        })
      });

      if (response.ok) {
        setShowToast(true);
        setTimeout(() => setShowToast(false), 2000);
      } else {
        alert('Failed to save. Please try again.');
      }
    } catch (error) {
      console.error('Save error:', error);
      alert('Failed to save. Please try again.');
    }
  };

  const handleSendToEtsy = () => {
    // TODO: Wire up to /api/etsy/sync when Etsy API approved
    alert('Etsy integration coming soon! For now, use Download or Copy.');
  };

  const handleCopyAll = () => {
    if (!optimizedContent) return;

    const allContent = `${optimizedContent.title}\n\n${optimizedContent.tags.join(', ')}\n\n${optimizedContent.description}`;
    navigator.clipboard.writeText(allContent);
    setShowToast(true);
    setTimeout(() => setShowToast(false), 2000);
  };

  if (isLoading) {
    return (
      <div style={{
        minHeight: '100vh',
        background: 'linear-gradient(135deg, #0F172A 0%, #1E293B 100%)',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center'
      }}>
        <p style={{ fontSize: '18px', color: '#9CA3AF' }}>Loading...</p>
      </div>
    );
  }

  if (!optimizedContent) {
    return (
      <div style={{
        minHeight: '100vh',
        background: 'linear-gradient(135deg, #0F172A 0%, #1E293B 100%)',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        flexDirection: 'column',
        gap: '20px'
      }}>
        <p style={{ fontSize: '18px', color: '#9CA3AF' }}>No optimization found</p>
        <button
          onClick={() => router.push('/upload')}
          style={{
            padding: '12px 24px',
            background: '#3B82F6',
            color: 'white',
            border: 'none',
            borderRadius: '8px',
            cursor: 'pointer'
          }}
        >
          Start New Optimization
        </button>
      </div>
    );
  }

  return (
    <div style={{
      minHeight: '100vh',
      background: 'linear-gradient(135deg, #0F172A 0%, #1E293B 100%)',
      paddingTop: '40px',
      paddingBottom: '80px'
    }}>
      {/* Toast Notification */}
      {showToast && (
        <div style={{
          position: 'fixed',
          top: '20px',
          right: '20px',
          background: 'linear-gradient(135deg, #10B981, #059669)',
          color: 'white',
          padding: '16px 24px',
          borderRadius: '8px',
          boxShadow: '0 8px 24px rgba(16, 185, 129, 0.4)',
          zIndex: 9999,
          fontSize: '16px',
          fontWeight: 600,
          display: 'flex',
          alignItems: 'center',
          gap: '12px'
        }}>
          <span style={{ fontSize: '24px' }}>✓</span>
          Success!
        </div>
      )}

      <Container>
        <div style={{ maxWidth: '900px', margin: '0 auto' }}>
          {/* Success Header */}
          <div style={{
            textAlign: 'center',
            marginBottom: '48px'
          }}>
            <div style={{
              width: '80px',
              height: '80px',
              background: 'linear-gradient(135deg, #10B981, #059669)',
              borderRadius: '50%',
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'center',
              fontSize: '48px',
              margin: '0 auto 24px',
              boxShadow: '0 8px 24px rgba(16, 185, 129, 0.4)'
            }}>
              ✓
            </div>

            <h1 style={{
              fontSize: '36px',
              fontWeight: 'bold',
              color: '#F9FAFB',
              marginBottom: '12px',
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'center',
              gap: '12px'
            }}>
              Your Listing is Optimized!
              <span
                title="Publish or save your optimized listing"
                style={{
                  width: '28px',
                  height: '28px',
                  background: '#3B82F6',
                  borderRadius: '50%',
                  display: 'inline-flex',
                  alignItems: 'center',
                  justifyContent: 'center',
                  fontSize: '16px',
                  cursor: 'help'
                }}
              >
                ℹ
              </span>
            </h1>
            <p style={{
              fontSize: '18px',
              color: '#9CA3AF'
            }}>
              Your listing score improved from 140 to {optimizedContent.score} out of {optimizedContent.maxScore}
            </p>
          </div>

          {/* Summary Card */}
          <Card>
            <div style={{ padding: '32px' }}>
              <h2 style={{
                fontSize: '24px',
                fontWeight: 'bold',
                color: '#F9FAFB',
                marginBottom: '24px'
              }}>
                📋 Optimization Summary
              </h2>

              {/* Photo Preview */}
              <div style={{
                marginBottom: '24px',
                textAlign: 'center'
              }}>
                <img
                  src={optimizedContent.photo}
                  alt="Optimized product"
                  style={{
                    width: '300px',
                    height: '300px',
                    objectFit: 'cover',
                    borderRadius: '12px',
                    margin: '0 auto',
                    boxShadow: '0 4px 12px rgba(0, 0, 0, 0.3)'
                  }}
                />
              </div>

              {/* Title */}
              <div style={{ marginBottom: '24px' }}>
                <h3 style={{
                  fontSize: '14px',
                  fontWeight: 600,
                  color: '#9CA3AF',
                  marginBottom: '8px'
                }}>
                  TITLE:
                </h3>
                <p style={{
                  fontSize: '18px',
                  color: '#F9FAFB',
                  fontWeight: 600,
                  lineHeight: 1.5
                }}>
                  {optimizedContent.title}
                </p>
              </div>

              {/* Tags */}
              <div style={{ marginBottom: '24px' }}>
                <h3 style={{
                  fontSize: '14px',
                  fontWeight: 600,
                  color: '#9CA3AF',
                  marginBottom: '8px'
                }}>
                  TAGS ({optimizedContent.tags.length}):
                </h3>
                <div style={{
                  display: 'flex',
                  flexWrap: 'wrap',
                  gap: '8px'
                }}>
                  {optimizedContent.tags.map((tag, index) => (
                    <span
                      key={index}
                      style={{
                        padding: '6px 12px',
                        background: '#3B82F6',
                        color: 'white',
                        borderRadius: '16px',
                        fontSize: '14px',
                        fontWeight: 500
                      }}
                    >
                      {tag}
                    </span>
                  ))}
                </div>
              </div>

              {/* Description Preview */}
              <div>
                <h3 style={{
                  fontSize: '14px',
                  fontWeight: 600,
                  color: '#9CA3AF',
                  marginBottom: '8px'
                }}>
                  DESCRIPTION:
                </h3>
                <div style={{
                  fontSize: '16px',
                  color: '#D1D5DB',
                  lineHeight: 1.7,
                  maxHeight: '150px',
                  overflowY: 'auto',
                  padding: '12px',
                  background: 'rgba(0, 0, 0, 0.3)',
                  borderRadius: '8px',
                  whiteSpace: 'pre-wrap'
                }}>
                  {optimizedContent.description.substring(0, 200)}...
                </div>
              </div>
            </div>
          </Card>

          {/* Action Buttons */}
          <div style={{
            marginTop: '40px',
            display: 'grid',
            gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))',
            gap: '16px'
          }}>
            {/* Download Text */}
            <button
              onClick={handleDownloadText}
              title="Download your optimized listing as a text file"
              style={{
                padding: '16px 24px',
                background: 'rgba(59, 130, 246, 0.1)',
                color: '#60A5FA',
                border: '1px solid #3B82F6',
                borderRadius: '8px',
                fontSize: '16px',
                fontWeight: 'bold',
                cursor: 'pointer',
                minHeight: '56px',
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'center',
                gap: '8px'
              }}
            >
              📥 Download Text
            </button>

            {/* Copy All */}
            <button
              onClick={handleCopyAll}
              title="Copy everything to clipboard"
              style={{
                padding: '16px 24px',
                background: 'rgba(139, 92, 246, 0.1)',
                color: '#A78BFA',
                border: '1px solid #8B5CF6',
                borderRadius: '8px',
                fontSize: '16px',
                fontWeight: 'bold',
                cursor: 'pointer',
                minHeight: '56px',
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'center',
                gap: '8px'
              }}
            >
              📋 Copy All
            </button>

            {/* Save to Account */}
            <button
              onClick={handleSaveToAccount}
              title="Save this optimization to your account for later"
              style={{
                padding: '16px 24px',
                background: 'rgba(16, 185, 129, 0.1)',
                color: '#34D399',
                border: '1px solid #10B981',
                borderRadius: '8px',
                fontSize: '16px',
                fontWeight: 'bold',
                cursor: 'pointer',
                minHeight: '56px',
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'center',
                gap: '8px'
              }}
            >
              💾 Save to Account
            </button>

            {/* Send to Etsy (Coming Soon) */}
            <button
              onClick={handleSendToEtsy}
              title="Automatically publish to your Etsy shop (coming soon)"
              disabled
              style={{
                padding: '16px 24px',
                background: 'rgba(100, 116, 139, 0.1)',
                color: '#64748B',
                border: '1px solid #475569',
                borderRadius: '8px',
                fontSize: '16px',
                fontWeight: 'bold',
                cursor: 'not-allowed',
                minHeight: '56px',
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'center',
                gap: '8px',
                opacity: 0.6
              }}
            >
              🚀 Send to Etsy
              <span style={{ fontSize: '12px', color: '#64748B' }}>(Soon)</span>
            </button>
          </div>

          {/* Next Steps */}
          <div style={{
            marginTop: '48px',
            display: 'flex',
            justifyContent: 'center',
            gap: '16px'
          }}>
            <button
              onClick={() => router.push('/')}
              style={{
                padding: '12px 32px',
                background: 'transparent',
                color: '#9CA3AF',
                border: '1px solid #374151',
                borderRadius: '8px',
                fontSize: '16px',
                fontWeight: 600,
                cursor: 'pointer',
                minHeight: '48px'
              }}
            >
              🏠 Back to Home
            </button>

            <button
              onClick={() => router.push('/upload')}
              style={{
                padding: '12px 32px',
                background: 'linear-gradient(135deg, #3B82F6, #10B981)',
                color: 'white',
                border: 'none',
                borderRadius: '8px',
                fontSize: '16px',
                fontWeight: 'bold',
                cursor: 'pointer',
                minHeight: '48px'
              }}
            >
              ✨ Optimize Another Listing
            </button>
          </div>
        </div>
      </Container>
    </div>
  );
}
